import fs from 'fs';
import path from 'path';

const noindexPath = path.join(process.cwd(), 'scripts', 'noindex_list.txt');
const outputPath = path.join(process.cwd(), 'lib', 'noindex-slugs.ts');

const content = fs.readFileSync(noindexPath, 'utf8');
const slugs = content.split('\n').map(s => s.trim()).filter(s => s);

const tsContent = `// Auto-generated by scripts/generate_noindex_constants.ts
export const NOINDEX_SLUGS = new Set<string>([
${slugs.map(s => `  '${s.replace(/'/g, "\\'")}'`).join(',\n')}
]);
`;

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, tsContent, 'utf8');

console.log(`✓ Generated NOINDEX_SLUGS with ${slugs.length} entries → lib/noindex-slugs.ts`);
