INSERT INTO problems (slug, formula, title, description, type) VALUES ('derivative-of-sin-x2', 'sin(x^2)', 'Derivative of sin(x^2)', 'Chain rule example with sine and x^2.', 'derivative');
INSERT INTO problems (slug, formula, title, description, type) VALUES ('derivative-of-x-e-x', 'x*e^x', 'Derivative of x*e^x', 'Product rule example with x and e^x.', 'derivative');
INSERT INTO problems (slug, formula, title, description, type) VALUES ('derivative-of-1-x', '1/x', 'Derivative of 1/x', 'Power rule example with 1/x.', 'derivative');
INSERT INTO problems (slug, formula, title, description, type) VALUES ('derivative-of-x2', 'x^2', 'Derivative of x^2', 'Fundamental power rule example.', 'derivative');
INSERT INTO problems (slug, formula, title, description, type) VALUES ('derivative-of-x3', 'x^3', 'Derivative of x^3', 'Fundamental power rule example.', 'derivative');
INSERT INTO problems (slug, formula, title, description, type) VALUES ('limit-of-sin-x-x', 'sin(x)/x', 'Limit of sin(x)/x', 'Special trigonometric limit example.', 'limit');
INSERT INTO problems (slug, formula, title, description, type) VALUES ('limit-of-e-x-1-x', '(e^x-1)/x', 'Limit of (e^x-1)/x', 'Exponential limit example using L''Hopital''s Rule.', 'limit');
INSERT INTO problems (slug, formula, title, description, type) VALUES ('integral-of-x-sin-x', 'x*sin(x)', 'Integral of x*sin(x)', 'Integration by parts example.', 'integral');
INSERT INTO problems (slug, formula, title, description, type) VALUES ('integral-of-x-e-x', 'x*e^x', 'Integral of x*e^x', 'Integration by parts example.', 'integral');
INSERT INTO problems (slug, formula, title, description, type) VALUES ('integral-of-x2-from-0-to-1', 'x^2', 'Integral of x^2 from 0 to 1', 'Definite integral example.', 'integral');
INSERT INTO problems (slug, formula, title, description, type) VALUES ('integral-of-sin-x-from-0-to-pi', 'sin(x)', 'Integral of sin(x) from 0 to pi', 'Definite trigonometric integral example.', 'integral');
INSERT INTO problems (slug, formula, title, description, type) VALUES ('derivative-of-x2-y2-25', 'x^2+y^2=25', 'Derivative of x^2+y^2=25', 'Implicit differentiation example.', 'derivative');
INSERT INTO problems (slug, formula, title, description, type) VALUES ('derivative-of-sin-xy-x', 'sin(x*y)=x', 'Derivative of sin(x*y)=x', 'Advanced implicit differentiation example.', 'derivative');
INSERT INTO problems (slug, formula, title, description, type) VALUES ('partial-derivative-of-x2y-xy2', 'x^2*y + x*y^2', 'Partial Derivative of x^2*y + x*y^2', 'Multivariable calculus example.', 'derivative');
INSERT INTO problems (slug, formula, title, description, type) VALUES ('partial-derivative-of-sin-xy', 'sin(x*y)', 'Partial Derivative of sin(x*y)', 'Multivariable calculus chain rule example.', 'derivative');
INSERT INTO problems (slug, formula, title, description, type) VALUES ('integral-of-x-cos-x2', 'x*cos(x^2)', 'Integral of x*cos(x^2)', 'U-substitution example.', 'integral');
INSERT INTO problems (slug, formula, title, description, type) VALUES ('integral-of-2x-x2-1', '2*x/(x^2+1)', 'Integral of 2*x/(x^2+1)', 'U-substitution example with logs.', 'integral');
INSERT INTO problems (slug, formula, title, description, type) VALUES ('derivative-of-x2-by-definition', 'x^2', 'Derivative of x^2 by Definition', 'Limit definition of the derivative example.', 'derivative');
INSERT INTO problems (slug, formula, title, description, type) VALUES ('derivative-of-3x-by-definition', '3*x', 'Derivative of 3*x by Definition', 'Limit definition of the derivative example.', 'derivative');
INSERT INTO problems (slug, formula, title, description, type) VALUES ('derivative-of-e-x', 'e^x', 'Derivative of e^x', 'Natural exponential derivative example.', 'derivative');
INSERT INTO problems (slug, formula, title, description, type) VALUES ('derivative-of-2-x', '2^x', 'Derivative of 2^x', 'General exponential derivative example.', 'derivative');
INSERT INTO problems (slug, formula, title, description, type) VALUES ('integral-of-x-from-0-to-2', 'x', 'Integral of x from 0 to 2', 'Base definite integral example.', 'integral');
INSERT INTO problems (slug, formula, title, description, type) VALUES ('integral-of-x2-from-1-to-3', 'x^2', 'Integral of x^2 from 1 to 3', 'Base definite integral example.', 'integral');
INSERT INTO problems (slug, formula, title, description, type) VALUES ('mvt-problem-1', 'x^2', 'Mean Value Theorem Example 1', 'Applying MVT to x^2.', 'derivative');
INSERT INTO problems (slug, formula, title, description, type) VALUES ('mvt-problem-2', 'x^3-x', 'Mean Value Theorem Example 2', 'Applying MVT to x^3-x.', 'derivative');